# Generated by Django 3.1.2 on 2020-10-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
